### ISSUE TITLE
低版本安卓webview不兼容

### ISSUE THREAD

**Issue by overofheight** [chrisguttandin/worker-timers#359] opened 2019-12-13 07:03 UTC
在低版本安卓webview下，开发者编译模式 webpack-dev-server下， 会报兼容性错误。Uncaught SyntaxError: Use of const in strict mode

**Comment by chrisguttandin** [comment] 2019-12-13 10:12
Hi @overofheight,

can you please provide some further details?

I tried to translate the message and from what I can tell it looks like an outdated webview is used which doesn't understand the const keyword. Are you using the ES5 bundle? If not that might already solve the problem. Only the modern ES2018 bundle should make use constant variables.

**Comment by chrisguttandin** [comment] 2020-01-21 01:10
Hi @overofheight, I'm going to close this issue now since there is no way for me to reproduce it.

Please let me know if the error persists and you have time to provide further information.

**Closed by chrisguttandin** 2020-01-21 01:10 UTC
